# DI for importer related setup

services:

  app.common.rootDirectory:
    class: \Phpsw\Website\Common\RootDirectory
    arguments: ['%rootDirectory%']


  app.common.personRepository:
    class: Phpsw\Website\Repository\InMemory\PersonRepository

