# DI for importer related setup

services:

  app.common.rootDirectory:
    class: \Phpsw\Website\Common\RootDirectory
    arguments: ['%rootDirectory%']


  app.common.personRepository:
    class: Phpsw\Website\Repository\InMemory\PersonRepository

  app.common.locationRepository:
    class: Phpsw\Website\Repository\InMemory\LocationRepository
    
  app.common.sponsorRepository:
    class: Phpsw\Website\Repository\InMemory\SponsorRepository
    
  app.common.websiteInfoRepository:
    class: Phpsw\Website\Repository\InMemory\WebsiteInfoRepository

  app.common.eventRepository:
    class: Phpsw\Website\Repository\InMemory\EventRepository
