#
# Configuration for the live app
#

parameters:

  # Location of base directory holding JSON data.
  importDataDirectory: "data"


  # Location of base directory holding web site output
  websiteBaseDirectory: "web"


imports:
  - { resource: services.yml }