#
# Configuration for the live app
#

imports:
  - { resource: secrets.yml }
  - { resource: services.yml }

parameters:

  # Location of base directory holding JSON data.
  importDataDirectory: "data"


  # Location of base directory holding web site output
  websiteBaseDirectory: "web"


