# DI for importer related setup

services:

  # Entry point to importer
  app.importer:
    class: \Phpsw\Website\Importer\Importer
    autowire: true

  # Form Building classes
  app.importer.formBuilder:
    class: \Phpsw\Website\Importer\EntityImporter\Form\FormBuilder
    autowire: true

  app.importer.formBuilderDependencyInjectionExtension:
    class: \Phpsw\Website\Importer\EntityImporter\Form\DependencyInjectionExtension

  # FormTypes - Each Entity requires on of these. These must be tagged FormType
  app.importer.formType.Person:
    class: \Phpsw\Website\Importer\EntityImporter\Form\PersonType
    autowire: true
    tags:
      - {name: "FormType", entityFqcn: 'Phpsw\Website\Entity\Person'}

  app.importer.formType.Location:
    class: \Phpsw\Website\Importer\EntityImporter\Form\LocationType
    autowire: true
    tags:
      - {name: "FormType", entityFqcn: 'Phpsw\Website\Entity\Location'}

  app.importer.formType.Sponsor:
    class: \Phpsw\Website\Importer\EntityImporter\Form\SponsorType
    autowire: true
    tags:
      - {name: "FormType", entityFqcn: 'Phpsw\Website\Entity\Sponsor'}

  app.importer.formType.WebsiteInfo:
    class: \Phpsw\Website\Importer\EntityImporter\Form\WebsiteInfoType
    autowire: true
    tags:
      - {name: "FormType", entityFqcn: 'Phpsw\Website\Entity\WebsiteInfo'}


  # Entity Importers - All entity importers must be tagged EntityImporter
  app.importer.personImporter:
    class: \Phpsw\Website\Importer\EntityImporter\EntityImporter
    arguments: ['@app.importer.formBuilder', '@app.common.personRepository', 'Phpsw\Website\Entity\Person']
    tags:
      - { name: "EntityImporter", directory: "%importDataDirectory%/people", order: 1 }

  app.importer.locationImporter:
    class: \Phpsw\Website\Importer\EntityImporter\EntityImporter
    arguments: ['@app.importer.formBuilder', '@app.common.locationRepository', 'Phpsw\Website\Entity\Location']
    tags:
      - { name: "EntityImporter", directory: "%importDataDirectory%/locations", order: 2 }

  app.importer.sponsorImporter:
    class: \Phpsw\Website\Importer\EntityImporter\EntityImporter
    arguments: ['@app.importer.formBuilder', '@app.common.sponsorRepository', 'Phpsw\Website\Entity\Sponsor']
    tags:
      - { name: "EntityImporter", directory: "%importDataDirectory%/sponsors", order: 3 }
      
  app.importer.websiteInfoImporter:
    class: \Phpsw\Website\Importer\EntityImporter\EntityImporter
    arguments: ['@app.importer.formBuilder', '@app.common.websiteInfoRepository', 'Phpsw\Website\Entity\WebsiteInfo']
    tags:
      - { name: "EntityImporter", directory: "%importDataDirectory%/website", order: 4 }
            