# Copy this file and rename it to secrets.yml, then fill in the required data.

# Goes without saying - never check your secrets.yml file into source control!

parameters:

  # Meetup API key - get yours from https://secure.meetup.com/meetup_api/key/
  meetupApiKey: ""