# DI for website generator related setup

services:

  # Entry point to website generator
  app.websiteGenerator:
    class: \Phpsw\Website\WebsiteGenerator\WebsiteGenerator
    autowire: true

  # Value object that holds the base directory for
  app.websiteGenerator.baseDirectory:
    class: \Phpsw\Website\WebsiteGenerator\WebsiteBaseDirectory
    arguments: ["%websiteBaseDirectory%"]

  app.websiteGenerator.twigWrapper:
    class: \Phpsw\Website\WebsiteGenerator\TemplateRenderer\TwigWrapper
    autowire: true


  # Website generator command
  app.websiteGenerator.command:
    class: \Phpsw\Website\WebsiteGenerator\GenerateWebsiteCommand
    autowire: true
    tags:
      - {name: "ConsoleCommand" }


