---
# Node
- name: Register NodeJS
  shell: 'curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -'
  changed_when: false

- name: Remove cmdtest
  apt:
    name: cmdtest
    state: absent

- name: Install Yarn APT key
  apt_key:
    data: "{{ lookup('file', 'pubkey.gpg') }}"
    state: present

- name: Add yarn repository
  apt_repository:
    repo: 'deb https://dl.yarnpkg.com/debian/ stable main'
    update_cache: yes

- name: Install packages
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - nodejs
    - yarn
  become: true
