---
nginx_user: www-data
app_user: phpsw

default_users:
- name: tadam
  password: '*'
  groups: sudo,ssh-users
  authorized_keys:
  - files/keys/tadam.pub
- name: dliddament
  password: '*'
  groups: sudo,ssh-users
  authorized_keys:
  - files/keys/dliddament.pub
- name: kzien
  password: '*'
  groups: sudo, ssh-users
  authorized_keys:
  - files/keys/kzien.pub

php_packages:
- php7.0-opcache
- php7.0-dom

php_xdebug: false
