---
- name: Install PHP CLI
  apt: pkg=php7.0-cli state=latest update_cache=yes cache_valid_time=3600

- name: Install PHP packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items: '{{ php_packages }}'

- name: Apply PHP CLI settings
  template: src=php.ini dest=/etc/php/7.0/cli/php.ini owner=root group=root mode=0644

# TODO: review security
- name: Ensure opcache file cache dir exists
  file: path='{{ php_cli_opcache_file_cache }}' owner=root group=root mode=0777 state=directory
  when: php_cli_opcache_file_cache_only == 1

- include: xdebug.yml
  when: php_xdebug
